@extends('layouts.master')

@section('title', 'Términos y condiciones de Carpoolear')
@section('body-class', 'body-acerca acerca-de-equipo')

@section('content')
<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-12 pt48">
                <h2>Términos y condiciones de Carpoolear</h2>
                
                <p><strong>&Uacute;ltima revisi&oacute;n: </strong><strong>9 de junio de 2020</strong></p>

                <p>En este documento se describen los T&eacute;rminos y Condiciones generales aplicables al uso de los servicios ofrecidos por Carpoolear<strong>&reg;</strong> mediante <a href="http://www.carpoolear.com.ar/app">www.carpoolear.com.ar/app</a> y la aplicaci&ograve;n Carpoolear (en adelante &ldquo;Carpoolear<strong>&reg;</strong>&rdquo;). Cualquier persona (en adelante &quot;Usuario&quot;) que desee usar o utilizar Carpoolear<strong>&reg;</strong> podr&aacute; hacerlo sujet&aacute;ndose a los T&eacute;rminos y Condiciones respectivos, junto con todas las dem&aacute;s pol&iacute;ticas y principios.</p>
                
                <p>Cualquier persona que no acepte estos t&eacute;rminos y condiciones generales, los cuales tienen un car&aacute;cter obligatorio y vinculante, no podr&aacute; utilizar Carpoolear<strong>&reg;</strong></p>
                
                <p>El Usuario debe leer, entender y aceptar todas las condiciones establecidas en los T&eacute;rminos y Condiciones Generales previo a su registraci&oacute;n como Usuario de Carpoolear<strong>&reg;</strong>. De continuar, est&aacute; aceptando expresamente y sin renunciar a ninguna cl&aacute;usula los presentes T&eacute;rminos y Condiciones.</p>
                
                <p>Carpoolear podr&aacute; modificar los T&eacute;rminos y Condiciones en cualquier momento y ser&aacute;n vinculantes desde su publicaci&oacute;n en la web www.carpoolear.com.ar&nbsp;</p>
                
                <p><strong>Usuarios</strong></p>
                
                <p>Los Servicios s&oacute;lo est&aacute;n disponibles para personas que tengan capacidad legal para contratar conforme la legislaci&oacute;n argentina. No podr&aacute;n utilizar Carpoolear<strong>&reg;</strong> las personas que no tengan esa capacidad, los menores de edad o Usuarios de Carpoolear<strong>&reg;</strong> que hayan sido suspendidos temporalmente, indefinidamente o permanentemente. El usuario reconoce ser mayor de 18 a&ntilde;os cuando se inscribe para usar Carpoolear<strong>&reg;</strong>. Respecto a Usuarios que se transporten con menores de edad, deber&aacute;n cumplir con las disposiciones de la SGT N&deg;43/2016, de la CNRT N&deg;1025/2016 y concordantes. El Usuario ser&aacute; el encargado exclusivo de hacer cumplir estas disposiciones y el responsable absoluto por su incumplimiento, sin perjuicio de las medidas que pueda tomar Carpoolear respecto a su suspensi&oacute;n temporal o permanente. El Usuario ser&aacute; responsable absoluto de todas las consecuencias derivadas del incumplimiento contractual de estos T&eacute;rminos y Condiciones, sobre las cosas a su cargo y/o las personas a su cuidado y por cualquier da&ntilde;o y/o perjuicio, sea mediante culpa o dolo.</p>
                
                <p><strong>El servicio</strong></p>
                
                <p>El servicio de punto de encuentro entre conductores y pasajeros ofrecido por Carpoolear<strong>&reg;</strong> es gratuito. Carpoolear<strong>&reg;</strong> se reserva el derecho de implementar nuevos servicios gratis o pagos, los cuales ser&aacute;n publicados en la web <a href="http://www.carpoolear.com.ar">www.carpoolear.com.ar</a> y los cuales el Usuario tendr&aacute; la posibilidad de aceptar o no. La aceptaci&oacute;n de cualquier nuevo servicio, gratuito o pago, constituye una condici&oacute;n excluyente para seguir siendo Usuario activo de Carpoolear<strong>&reg;</strong>&nbsp;</p>
                
                <p>Carpoolear<strong>&reg;</strong> se reserva el derecho de inhabilitar o suspender usuarios, sin que est&eacute; obligado a comunicar o exponer las razones de su decisi&oacute;n y sin que ello genere alg&uacute;n derecho a indemnizaci&oacute;n, resarcimiento o reparaci&oacute;n.</p>
                
                <p>Sin perjuicio de otras medidas, Carpoolear<strong>&reg;</strong>podr&aacute; advertir, suspender en forma temporal o permanente, inhabilitar un Usuario y/o una publicaci&oacute;n, iniciar las acciones que estime pertinentes y/o suspender la prestaci&oacute;n de sus Servicios si : (1) se quebrantara alguna ley, o cualquiera de las estipulaciones de los T&eacute;rminos y Condiciones y dem&aacute;s pol&iacute;ticas de Carpoolear<strong>&reg;</strong>; (2) si incumpliera sus compromisos como Usuario; (3) si se incurriera, a criterio de Carpoolear<strong>&reg;</strong>, en conductas <strong>que fueren en contra del ordenamiento jur&iacute;dico o el que excede los l&iacute;mites impuestos por la buena fe, la moral y las buenas costumbres y/</strong><strong> o actos dolosos o fraudulentos </strong><strong>tendientes a perjudicar tanto a los dem&aacute;s Usuarios como a Carpoolear</strong><strong>&reg;</strong>; (4) no pudiera verificarse la identidad del Usuario o cualquier informaci&oacute;n proporcionada por el mismo fuere err&oacute;nea; (5) Carpoolear<strong>&reg;</strong> entendiera que las publicaciones u otras acciones pueden ser causa de responsabilidad para el Usuario que las public&oacute;, para Carpoolear<strong>&reg;</strong> o para los Usuarios. En el caso de la suspensi&oacute;n o inhabilitaci&oacute;n de un Usuario, todos las publicaciones ser&aacute;n removidas del sistema, salvaguardando correspondientemente y seg&uacute;n la legislaci&oacute;n en materia de privacidad, todos aquellos datos que Carpoolear est&eacute; obligado a brindar para coadyuvar en el avance de cualquier investigaci&oacute;n civil, penal o de cualquier &iacute;ndole.</p>
                
                <p><strong>El uso del servicio</strong></p>
                
                <p>Un viaje en el que los usuarios comparten un autom&oacute;vil, es el resultado de un acuerdo previo entre un conductor y los pasajeros, los usuarios del servicio (tanto conductor como pasajeros mayores de edad) act&uacute;an bajo su plena responsabilidad. Como tal, Carpoolear<strong>&reg;</strong> no se responsabiliza por el cumplimiento real del viaje ni de las condiciones propuestas por los usuarios o conductores, ni de cualquier consecuencia, prevista o imprevista, que surgiera del mismo. El servicio brindado por Carpoolear<strong>&reg;</strong> se limita a conectar a usuarios (quienes pueden actuar como pasajeros o conductores indistintamente) por intermedio de la aplicaci&ograve;n puesta a disposici&oacute;n de los mismos.</p>
                
                <p>Carpoolear no asume la realizaci&oacute;n, titularidad, ni responsabilidad de la prestaci&oacute;n de los servicios que intermedia, ni frente a los usuarios de los mismos, ni frente a terceros.</p>
                
                <p><strong>Seguro automotor correspondiente</strong></p>
                
                <p>Previamente a que el Usuario proponga un viaje como conductor, primero debe comprobar que la vigencia de su seguro automotor abarque toda la duraci&oacute;n del viaje. La ley de tr&aacute;nsito indica como requisito para circular con automotor que lleve el comprobante de seguro en vigencia, entre otras cosas. Un conductor sin seguro es plenamente responsable de los da&ntilde;os causados a sus pasajeros en caso de accidente. Carpoolear<strong>&reg; </strong>no se responsabiliza por las consecuencias, tanto para el conductor como para los pasajeros o cualquier tercero, que tenga un viaje no asegurado por el conductor; como as&iacute; tampoco se responsabiliza de forma parcial o total por cualquier da&ntilde;o y/o perjuicio f&iacute;sico, psicol&oacute;gico, material, o de cualquier &iacute;ndole a las personas o cosas que deriven de esas consecuencias, ni se constituye en garante, fiador o responsable solidario de los responsables principales que por su impericia, negligencia, falta de observancia a sus deberes, culpa o dolo hayan generado dichos da&ntilde;os y/o perjuicios. Los pasajeros tendr&aacute;n la responsabilidad absoluta de controlar el estado del autom&oacute;vil, del conductor y del autom&oacute;vil en el que viajar&aacute;n, sin posibilidad de reclamo alguna a Carpoolear<strong>&reg; </strong>o a sus miembros.</p>
                
                <p>Se informa a los usuarios que las compa&ntilde;&iacute;as de seguros pueden negarse a cubrir cualquier da&ntilde;o ocurrido en un viaje durante el cual el conductor hubiera pedido a los pasajeros una participaci&oacute;n econ&oacute;mica mayor que la establecida por la divisi&oacute;n de gastos del viaje (a los efectos de la interpretaci&oacute;n de &eacute;stos T&eacute;rminos y Condiciones, y de ahora en adelante, gastos de viaje se consideran solamente combustible y peaje/s). El conductor que solicitara que los dem&aacute;s usuarios de un viaje contribuyan sumas mayores a las resultantes de la divisi&oacute;n de los gastos del viaje entre todos los integrantes de dicho viaje, incurre en falta grave a estos T&eacute;rminos y Condiciones, bajo apercibimiento de ser dado de baja definitivamente de la aplicaci&ograve;n a criterio exclusivo de Carpoolear<strong>&reg;</strong>, no obstante las sanciones legales correspondientes por transporte ilegal de pasajeros y/o la falta de cobertura de su seguro contratado.</p>
                
                <p>El Conductor de un viaje podr&aacute; solicitar una colaboraci&ograve;n a los gastos de viaje a los dem&aacute;s Usuarios en la coordinaci&oacute;n previa. Siendo la colaboraci&ograve;n maxima igual a gastos de viaje divididos por la cantidad de personas total en viaje. Asimismo, los Usuarios pueden solicitar que la divisi&oacute;n de gastos de viaje se realicen con la presentaci&oacute;n de los tickets o facturas asociados al mismo en la coordinacion previa del viaje. Dicha solicitud no puede ser negada o no respondida por ning&uacute;n otro Usuario, so pena de incurrir en falta a estos T&eacute;rminos y Condiciones y posterior sanci&oacute;n que podr&aacute; aplicar Carpoolear seg&uacute;n la gravedad de la acci&oacute;n o la repetici&oacute;n de la misma por el mismo Usuario como usuario de Carpoolear<strong>&reg;</strong>.</p>
                
                <p>Carpoolear no tiene responsabilidad en la definici&oacute;n de los gastos del viaje. Es responsabilidad exclusiva de los usuarios participantes del viaje, tanto pasajeros como conductor, que en caso de haber participaci&oacute;n econ&oacute;mica no sea mayor a la establecida por la divisi&oacute;n de gastos del viaje para mantener la validez del seguro asociado al veh&iacute;culo con el que se realiz&oacute; el viaje compartido y no incumplir con la normativa vigente en materia de transporte en la Rep&uacute;blica Argentina.</p>
                
                <p><strong>Interrupciones y fallas del servicio</strong></p>
                
                <p>Carpoolear<strong>&reg;</strong> pretende ofrecer el servicio de forma ininterrumpida. No obstante, puede ocurrir que el acceso a la web o al servicio se interrumpa en el curso de operaciones de mantenimiento, actualizaciones hardware y software, de reparaciones de emergencia de la web, o debido a circunstancias fuera del control de Carpoolear<strong>&reg;</strong> (como falla de Internet o problemas de Facebook). Es por eso que Carpoolear<strong>&reg;</strong> no garantiza el acceso y uso continuado o ininterrumpido de su servicio. Los Usuarios reconocen y aceptan que Carpoolear<strong>&reg;</strong> no asume ninguna responsabilidad hacia &eacute;l por cualquier falta, suspensi&oacute;n o interrupci&oacute;n de la web o del servicio.</p>
                
                <p>Carpoolear<strong>&reg;</strong> no se responsabiliza por cualquier da&ntilde;o, perjuicio o p&eacute;rdida al Usuario causados por fallas en el sistema, en el servidor o en Internet. Carpoolear<strong>&reg;</strong> tampoco ser&aacute; responsable por cualquier virus que pudiera infectar el equipo de los Usuarios como consecuencia del acceso, uso o examen de su aplicacion o a ra&iacute;z de cualquier transferencia de datos, archivos, im&aacute;genes, textos, o audio contenidos en el mismo. Los Usuarios no podr&aacute;n adjudicarle a Carpoolear responsabilidad alguna ni exigir pago por lucro cesante, en virtud de perjuicios resultantes de dificultades t&eacute;cnicas o fallas en los sistemas o en Internet.</p>
                
                <p><strong>Violaciones del sistema</strong></p>
                
                <p>Est&aacute; terminantemente prohibida cualquier acci&oacute;n, uso de dispositivo, software, u otro medio tendiente a interferir tanto en las actividades y operatoria de Carpoolear<strong>&reg;</strong> como en descripciones o bases de datos asociadas a Carpoolear<strong>&reg;</strong>. Cualquier intromisi&oacute;n, tentativa o actividad violatoria o contraria a las leyes sobre derecho de propiedad intelectual y/o a las prohibiciones estipuladas en este contrato har&aacute;n pasible a su responsable de las acciones legales penales y civiles de da&ntilde;os y perjuicios pertinentes, y a las sanciones previstas por este acuerdo, as&iacute; como lo har&aacute; responsable de indemnizar los da&ntilde;os ocasionados.</p>
                
                <p><strong>Propiedad intelectual</strong></p>
                
                <p>Carpoolear<strong>&reg; </strong>es un proyecto sin fines de lucro propiedad de la Asociaci&oacute;n Civil Soluciones Tecnol&oacute;gicas Sustentables Rosario (en adelante &ldquo;STS Rosario&rdquo;) bajo Licencia N&ordm; 2.850.394. Prohibido todo uso indebido y/o uso con fines de lucro y/o reproducci&oacute;n y por cualquier medio de su imagen, logo, programas, bases de datos, aplicaci&ograve;n, redes, archivos que permiten al Usuario hacer uso de Carpoolear<strong>&reg;</strong>, contenido audiovisual digital, sin la autorizaci&oacute;n debida de STS Rosario quien es propietaria absoluta de dichos activos y derechos sobre los mismos. Los mismos est&aacute;n protegidas por las leyes y los tratados internacionales de derecho de autor, marcas, patentes, modelos y dise&ntilde;os industriales.&nbsp;</p>
                
                <p><strong>CL&Aacute;USULA ARBITRAL</strong></p>
                
                <p>Toda cuesti&oacute;n que se suscitare entre las partes por cualquier motivo relacionado con estos T&eacute;rminos y Condiciones, incluyendo, entre otras cuestiones, su validez, interpretaci&oacute;n, alcances, cumplimiento, resoluci&oacute;n o, asimismo, los reclamos a los que diere lugar su incumplimiento, se resolver&aacute;n definitivamente por el Tribunal de Arbitraje del Colegio de Abogados de Rosario, de acuerdo con el Reglamento y las Normas Complementarias aplicables al arbitraje de derecho aprobados por la Instituci&oacute;n, que las partes declaran conocer.</p>
                
                <p>Copyright &copy; 2017 Asociaci&oacute;n Civil Soluciones Tecnol&oacute;gicas Sustentables Rosario. Todos los derechos reservados.</p>
                
                <p>&nbsp;</p>
                
            </div>
        </div>
    </div>
</section>
@endsection
